# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Docente', '0001_initial'),
        ('Alumno', '0003_auto_20171127_1718'),
        ('Curso', '0001_initial'),
        ('Categoria', '0001_initial'),
        ('Especialidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_matricula', models.CharField(max_length=10, unique=True)),
                ('mfecha_matricula', models.DateField(blank=True, null=True)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumno.Alumno')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Categoria.Categoria')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Curso.Curso')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Docente.Docente')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Especialidad.Especialidad')),
            ],
        ),
    ]
