# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0002_auto_20171127_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='cod_alu',
            new_name='cod_alumno',
        ),
    ]
